### ISSUE TITLE
Rake fails on Mac OS X 10.11.6 with RVM 1.27.0 and Ruby 1.9.3p551

### ISSUE THREAD

**Issue by asbjornu** [labocho/movable_type_format#1]
After having [installed RVM and Ruby according to this blog post](https://www.moncefbelyamani.com/how-to-install-xcode-homebrew-git-rvm-ruby-on-mac/), running `bundle install` and then `rake -vt` in the repository yields the following exception:

```shell
WARNING: 'require 'rake/rdoctask'' is deprecated.  Please use 'require 'rdoc/task' (in RDoc 2.4.2+)' instead.
    at /Users/bitbear/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/rake/rdoctask.rb
** Invoke default (first_time)
** Invoke spec (first_time)
** Execute spec
/Users/bitbear/.rvm/rubies/ruby-1.9.3-p551/bin/ruby -S bundle exec rspec "spec/movable_type_format/entry_spec.rb" "spec/movable_type_format/parser_spec.rb" "spec/movable_type_format_spec.rb"
/Users/bitbear/.rvm/gems/ruby-1.9.3-p551/gems/rspec-core-2.3.1/lib/rspec/core/configuration.rb:253:in `rescue in debug=':  (RuntimeError)
**************************************************
You must install ruby-debug to run rspec with the --debug option.

If you have ruby-debug installed as a ruby gem, then you need to either
require 'rubygems' or configure the RUBYOPT environment variable with
the value 'rubygems'.
**************************************************
	from /Users/bitbear/.rvm/gems/ruby-1.9.3-p551/gems/rspec-core-2.3.1/lib/rspec/core/configuration.rb:241:in `debug='
	from /Users/bitbear/.rvm/gems/ruby-1.9.3-p551/gems/rspec-core-2.3.1/lib/rspec/core/configuration_options.rb:22:in `block in configure'
	from /Users/bitbear/.rvm/gems/ruby-1.9.3-p551/gems/rspec-core-2.3.1/lib/rspec/core/configuration_options.rb:21:in `each'
	from /Users/bitbear/.rvm/gems/ruby-1.9.3-p551/gems/rspec-core-2.3.1/lib/rspec/core/configuration_options.rb:21:in `configure'
	from /Users/bitbear/.rvm/gems/ruby-1.9.3-p551/gems/rspec-core-2.3.1/lib/rspec/core/command_line.rb:17:in `run'
	from /Users/bitbear/.rvm/gems/ruby-1.9.3-p551/gems/rspec-core-2.3.1/lib/rspec/core/runner.rb:55:in `run_in_process'
	from /Users/bitbear/.rvm/gems/ruby-1.9.3-p551/gems/rspec-core-2.3.1/lib/rspec/core/runner.rb:46:in `run'
	from /Users/bitbear/.rvm/gems/ruby-1.9.3-p551/gems/rspec-core-2.3.1/lib/rspec/core/runner.rb:10:in `block in autorun'
rake aborted!
ruby -S bundle exec rspec "spec/movable_type_format/entry_spec.rb" "spec/movable_type_format/parser_spec.rb" "spec/movable_type_format_spec.rb" failed
/Users/bitbear/.rvm/gems/ruby-1.9.3-p551/gems/rspec-core-2.3.1/lib/rspec/core/rake_task.rb:139:in `rescue in block (2 levels) in initialize'
/Users/bitbear/.rvm/gems/ruby-1.9.3-p551/gems/rspec-core-2.3.1/lib/rspec/core/rake_task.rb:135:in `block (2 levels) in initialize'
/Users/bitbear/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/rake/file_utils_ext.rb:60:in `verbose'
/Users/bitbear/.rvm/gems/ruby-1.9.3-p551/gems/rspec-core-2.3.1/lib/rspec/core/rake_task.rb:131:in `block in initialize'
/Users/bitbear/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/rake/task.rb:205:in `call'
/Users/bitbear/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/rake/task.rb:205:in `block in execute'
/Users/bitbear/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/rake/task.rb:200:in `each'
/Users/bitbear/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/rake/task.rb:200:in `execute'
/Users/bitbear/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/rake/task.rb:158:in `block in invoke_with_call_chain'
/Users/bitbear/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/Users/bitbear/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/rake/task.rb:151:in `invoke_with_call_chain'
/Users/bitbear/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/rake/task.rb:176:in `block in invoke_prerequisites'
/Users/bitbear/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/rake/task.rb:174:in `each'
/Users/bitbear/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/rake/task.rb:174:in `invoke_prerequisites'
/Users/bitbear/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/rake/task.rb:157:in `block in invoke_with_call_chain'
/Users/bitbear/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/Users/bitbear/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/rake/task.rb:151:in `invoke_with_call_chain'
/Users/bitbear/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/rake/task.rb:144:in `invoke'
/Users/bitbear/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/rake/application.rb:116:in `invoke_task'
/Users/bitbear/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/rake/application.rb:94:in `block (2 levels) in top_level'
/Users/bitbear/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/rake/application.rb:94:in `each'
/Users/bitbear/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/rake/application.rb:94:in `block in top_level'
/Users/bitbear/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/rake/application.rb:133:in `standard_exception_handling'
/Users/bitbear/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/rake/application.rb:88:in `top_level'
/Users/bitbear/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/rake/application.rb:66:in `block in run'
/Users/bitbear/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/rake/application.rb:133:in `standard_exception_handling'
/Users/bitbear/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/rake/application.rb:63:in `run'
/Users/bitbear/.rvm/gems/ruby-1.9.3-p551@global/gems/rake-0.9.2.2/bin/rake:32:in `<top (required)>'
/Users/bitbear/.rvm/gems/ruby-1.9.3-p551@global/bin/rake:23:in `load'
/Users/bitbear/.rvm/gems/ruby-1.9.3-p551@global/bin/rake:23:in `<main>'
/Users/bitbear/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `eval'
/Users/bitbear/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => default => spec
```

I can't really find a concrete error message in there, just a very long stack trace. I therefore don't really know where to start figuring out this problem. Ideas?

**Comment by labocho** [comment]
Sorry. `.rspec` caused this error. I fixed it.
Please `git pull && bundle` and retry.

**Comment by asbjornu** [comment]
Excellent, thanks! Now I just need to figure out how to execute the gem... ;-)

**Comment by labocho** [comment]
Added `examples` and better `README.md` :)

**Comment by asbjornu** [comment]
@labocho: Awesome, thanks! Is it currently not possible to execute the gem from the command line? I know so little about Ruby that I don't know if that's possible at all. Anyway, that's my preferred way to use it; not having to develop my own Ruby script, but just pipe the contents from a Movable Type export file to the gem and get something more manageable out in the other end. :)

**Comment by labocho** [comment]
> something more manageable out

like JSON?
Do you need a command that is like below?

```
$ cat exported.txt | mt2json
{ "title": "Title",
  "body": "body...",
  ...
}
```

**Comment by asbjornu** [comment]
JSON would be very helpful, yes.

**Comment by labocho** [comment]
@asbjornu `mt2json` command is now available!
Please `git pull && bundle install && bundle exec rake install`. And `cat exported.txt | mt2json`.

**Comment by asbjornu** [comment]
Wow, fantastic! Thanks! 😃
